
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: forex
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  api:
    build: ./api
    env_file: .env
    environment:
      DATABASE_URL: postgres://app:${POSTGRES_PASSWORD}@db:5432/forex
      REDIS_URL: redis://redis:6379/0
      ML_BASE_URL: http://ml:8000
      RAILS_ENV: development
    depends_on:
      - db
      - redis
      - ml
    ports:
      - "3000:3000"
    command: >
      bash -lc "bundle exec rails db:prepare &&
                bundle exec rails s -b 0.0.0.0 -p 3000"

  worker:
    build: ./api
    env_file: .env
    environment:
      DATABASE_URL: postgres://app:${POSTGRES_PASSWORD}@db:5432/forex
      REDIS_URL: redis://redis:6379/0
      ML_BASE_URL: http://ml:8000
      RAILS_ENV: development
    depends_on:
      - db
      - redis
      - ml
    command: bash -lc "bundle exec sidekiq"

  ml:
    build: ./ml_service
    volumes:
      - ./models:/models
    ports:
      - "8000:8000"

volumes:
  pgdata:
